version: '3'

services:
  bot:
    build: ./bot
    command: "startBot"
    volumes:
      - .:/go/src
  server:
    build: ./server
    command: "startServer"
    volumes:
      - .:/go/src
    ports:
    - "8080:8080"
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  rabbit:
    build: ./queue
    ports:
      - "15672:15672"
      - "5672:5672"
