version: '3'

services:
  server:
    build: ./server
    volumes:
      - .:/go/src
    ports:
    - "8080:8080"
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
